In [1]:
import numpy as np


In [4]:
layers = [2,2,1]
for i in np.arange(0, len(layers) - 2):
    w = np.random.rand(layers[i] + 1, layers[i+1] + 1)
    print(w)

[[0.64608077 0.17818945 0.40642283]
 [0.09171334 0.15750096 0.86464759]
 [0.81548351 0.02300296 0.36554124]]


In [35]:
class NeuralNetwork:
    def __init__(self, layers, alpha=0.1):
            # Khởi tạo ma trận trọng số và lưu kiến trúc mạng cũng như learning rate
            self.W = []
            self.layers = layers
            self.alpha = alpha

            for i in np.arange(0, len(layers) - 2):
                # initial weight and bias 
                w = np.random.randn(layers[i] + 1, layers[i+1] + 1)
                self.W.append(w / np.sqrt(layers[i]))

            w = np.random.randn(layers[-2] + 1, layers[-1])
            self.W.append(w / np.sqrt(layers[-2]))
            print(self.W)
            for w in self.W:
                print(w.shape)
nn = NeuralNetwork((2,2,1))

[array([[-0.23100238,  0.08068682, -0.77911371],
       [-0.39935376, -0.32448822, -0.24332883],
       [-0.36884501, -0.36223824,  2.05996274]]), array([[-1.73430048],
       [-1.19177133],
       [-0.80823226]])]
(3, 3)
(3, 1)


In [21]:
X = np.array([[0,0], 
              [0,1], 
              [1,0], 
              [1,1]])
p = np.atleast_2d(X)
#p = np.c_[p, np.ones((p.shape[0]))]
#p

In [22]:
p

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])